magnum-ten.midi: gabrieli-giovanni-o-magnum-mysterium-C1-c4.mid Makefile
	midiconv.py -tv 3 1.2 5 -tv -1 0.8 0 $< $@

magnum-noten.midi: gabrieli-giovanni-o-magnum-mysterium.mid Makefile
	midiconv.py -tv 3 0 0 -tv -1 1 0 $< $@
