#

hasse-mia_cara_anzoletta.pdf: Hasse_Johann_Adolf_-_Mia_Cara_Anzoletta.pdf hasse-mia_cara.ann
	antpdf.py -i hasse-mia_cara.ann Hasse_Johann_Adolf_-_Mia_Cara_Anzoletta.pdf $@

myrna_cara.pdf: Hasse_Johann_Adolf_-_Mia_Cara_Anzoletta.pdf myrna_cara.ann
	antpdf.py -i myrna_cara.ann Hasse_Johann_Adolf_-_Mia_Cara_Anzoletta.pdf $@

