#!/bin/bash

set -u
wg ()
{
   wget  http://www.dycom-il.com/b/${1}
   rc=$?
   if [[ ${rc} -ne 0 ]]
   then
     echo failed 1>&2
     exit ${rc}
   fi
}

wg braun-kohelet-1-bas.mid
wg braun-kohelet-1-ten.mid
wg braun-kohelet-1-alt.mid
wg braun-kohelet-1-sop1.mid
wg braun-kohelet-1.mid
wg braun-kohelet-1-sop2.mid
wg braun-kohelet-2a-bas.mid
wg braun-kohelet-2a-ten.mid
wg braun-kohelet-2a-alt.mid
wg braun-kohelet-2a-sop1.mid
wg braun-kohelet-2a.mid
wg braun-kohelet-2a-sop2.mid
wg braun-kohelet-2b-bas.mid
wg braun-kohelet-2b-ten.mid
wg braun-kohelet-2b-alt.mid
wg braun-kohelet-2b-sop1.mid
wg braun-kohelet-2b.mid
wg braun-kohelet-2b-sop2.mid
wg braun-kohelet-2c-bas.mid
wg braun-kohelet-2c-ten.mid
wg braun-kohelet-2c-alt.mid
wg braun-kohelet-2c-sop1.mid
wg braun-kohelet-2c.mid
wg braun-kohelet-2c-sop2.mid
wg braun-kohelet-2d-bas.mid
wg braun-kohelet-2d-ten.mid
wg braun-kohelet-2d-alt.mid
wg braun-kohelet-2d-sop1.mid
wg braun-kohelet-2d.mid
wg braun-kohelet-2d-sop2.mid
wg braun-kohelet-3a-bas.mid
wg braun-kohelet-3a-ten.mid
wg braun-kohelet-3a-alt.mid
wg braun-kohelet-3a-sop1.mid
wg braun-kohelet-3a.mid
wg braun-kohelet-3a-sop2.mid
wg braun-kohelet-3b-bas.mid
wg braun-kohelet-3b-ten.mid
wg braun-kohelet-3b-alt.mid
wg braun-kohelet-3b-sop1.mid
wg braun-kohelet-3b.mid
wg braun-kohelet-3b-sop2.mid
wg braun-kohelet-4a-bas.mid
wg braun-kohelet-4a-ten.mid
wg braun-kohelet-4a-alt.mid
wg braun-kohelet-4a-sop1.mid
wg braun-kohelet-4a.mid
wg braun-kohelet-4a-sop2.mid
wg braun-kohelet-4b-bas.mid
wg braun-kohelet-4b-ten.mid
wg braun-kohelet-4b-alt.mid
wg braun-kohelet-4b-sop1.mid
wg braun-kohelet-4b.mid
wg braun-kohelet-4b-sop2.mid
wg braun-kohelet-4b-bar.mid
wg braun-kohelet-4c-bas.mid
wg braun-kohelet-4c-ten.mid
wg braun-kohelet-4c-alt.mid
wg braun-kohelet-4c-sop1.mid
wg braun-kohelet-4c.mid
wg braun-kohelet-4c-sop2.mid
wg braun-kohelet-5a-bas.mid
wg braun-kohelet-5a-ten.mid
wg braun-kohelet-5a-alt.mid
wg braun-kohelet-5a-sop1.mid
wg braun-kohelet-5a.mid
wg braun-kohelet-5a-sop2.mid
wg braun-kohelet-5b-bas.mid
wg braun-kohelet-5b-ten.mid
wg braun-kohelet-5b-alt.mid
wg braun-kohelet-5b-sop1.mid
wg braun-kohelet-5b.mid
wg braun-kohelet-5b-sop2.mid
wg braun-kohelet-5c-bas.mid
wg braun-kohelet-5c-ten.mid
wg braun-kohelet-5c-alt.mid
wg braun-kohelet-5c-sop1.mid
wg braun-kohelet-5c.mid
wg braun-kohelet-5c-sop2.mid
wg braun-kohelet-6a-bas.mid
wg braun-kohelet-6a-ten.mid
wg braun-kohelet-6a-alt.mid
wg braun-kohelet-6a-sop1.mid
wg braun-kohelet-6a.mid
wg braun-kohelet-6a-sop2.mid
wg braun-kohelet-6b-bas.mid
wg braun-kohelet-6b-ten.mid
wg braun-kohelet-6b-alt.mid
wg braun-kohelet-6b-sop1.mid
wg braun-kohelet-6b.mid
wg braun-kohelet-6b-sop2.mid
wg braun-kohelet-6c-bas.mid
wg braun-kohelet-6c-ten.mid
wg braun-kohelet-6c-alt.mid
wg braun-kohelet-6c-sop1.mid
wg braun-kohelet-6c.mid
wg braun-kohelet-6c-sop2.mid
wg braun-kohelet-6d-bas.mid
wg braun-kohelet-6d-ten.mid
wg braun-kohelet-6d-alt.mid
wg braun-kohelet-6d-sop1.mid
wg braun-kohelet-6d.mid
wg braun-kohelet-6d-sop2.mid
