# Author:  Yotam Medini  yotam.medini@gmail.com -- Created: 2016/August/06

rutter-magnificat-mvt1.pdf: 00.Magnificat.pdf
	cpdf $< 1-22 -o $@

rutter-magnificat-mvt1-a3.pdf: rutter-magnificat-mvt1.pdf
	bookletimposer -o $@ -a -p 2x1 -f A3 $<
