# Author:  Yotam Medini  yotam.medini@gmail.com -- Created: 2017/June/17

TARGETS = \
	1-noten.midi \
	2a-noten.midi \
	2b-noten.midi \
	2c-noten.midi \
	3a-noten.midi \
	3b-noten.midi \
	3c-noten.midi \
	4-noten.midi \
	5-noten.midi \
	6a-noten.midi \
	6b-noten.midi \
	6c-noten.midi \
	7a-noten.midi \
	7b-noten.midi \

all: ${TARGETS}

clean:
	rm -f ${TARGETS}

1-noten.midi:   ../brgreq1.mid
	midiconv.py -tv 3 0 0 $< $@

2a-noten.midi:  ../brgreq2a.mid
	midiconv.py -tv 3 0 0 $< $@

2b-noten.midi:  ../brgreq2b.mid
	midiconv.py -tv 3 0 0 $< $@

2c-noten.midi:  ../brgreq2c.mid
	midiconv.py -tv 3 0 0 $< $@

3a-noten.midi:  ../brgreq3a.mid
	midiconv.py -tv 3 0 0 $< $@

3b-noten.midi:  ../brgreq3b.mid
	midiconv.py -tv 3 0 0 $< $@

3c-noten.midi:  ../brgreq3c.mid
	midiconv.py -tv 3 0 0 $< $@

4-noten.midi:   ../brgreq4.mid
	midiconv.py -tv 3 0 0 $< $@

5-noten.midi:   ../brgreq5.mid
	midiconv.py -tv 3 0 0 $< $@

6a-noten.midi:  ../brgreq6a.mid
	midiconv.py -tv 3 0 0 $< $@

6b-noten.midi:  ../brgreq6b.mid
	midiconv.py -tv 3 0 0 $< $@

6c-noten.midi:  ../brgreq6c.mid
	midiconv.py -tv 3 0 0 $< $@

7a-noten.midi:  ../brgreq7a.mid
	midiconv.py -tv 3 0 0 $< $@

7b-noten.midi:  ../brgreq7b.mid
	midiconv.py -tv 3 0 0 $< $@
