1-requiem-noten.midi: ../Verdi_Requiem_01Requiem.mid
	midiconv.py -tv 7 0 0 -tv -1 1 0 $< $@

2a-diesira-noten.midi: ../VERDI_REQUIEM_02a_Dies_irae.mid
	midiconv.py -tv 5 0 0 -tv 6 0 0 -tv -1 1 0 $< $@

2b-tubamiru-noten.midi: ../VERDI_REQUIEM_02b_TUBA_MIRU.mid
	midiconv.py -tv 3 0 0 -tv -1 1 0 $< $@

2c-liberscriptus-noten.midi: ../Verdi_Requiem_02c_Liber_Scriptus.mid
	midiconv.py -tv 3 0 0 -tv -1 1 0 $< $@

2e-rextremende-noten.midi: ../VERDI_REQUIEM_02e_Rex_Tremende.mid
	midiconv.py -tv 6 0 0 -tv 7 0 0 -tv 8 0 0 -tv -1 1 0 $< $@

2h-confutatis-noten.midi: ../verdi_requiem_02h_CONFUTAT.mid
	midiconv.py -tv 5 0 0 -tv 6 0 0 -tv -1 1 0 $< $@

2i-lacrymosa-noten.midi: ../verdi_requiem_02i_Lacrymosa.mid
	midiconv.py -tv 8 0 0 -tv -1 1 0 $< $@

4-sanctus-noten.midi: ../verdi_requiem_04_sanctus.mid
	midiconv.py -tv 3 0 0 -tv 7 0 0 -tv -1 1 0 $< $@

5-agnusdei-noten.midi: ../VERDI_REQUIEM_05_Agnus_Dei.mid
	midiconv.py -tv 5 0 0 -tv -1 1 0 $< $@

7-liberame-a-noten.midi: ../VERDI_REQUIEM_07a_Libera_Me.mid
	midiconv.py -tv 5 0 0 -tv 6 0 0 -tv -1 1 0 $< $@

7-liberame-b-noten.midi: ../VERDI_REQUIEM_07b_Libera_Me.mid
	midiconv.py -tv 4 0 0 -tv -1 1 0 $< $@

7-liberame-c-noten.midi: ../VERDI_REQUIEM_07c_Libera_Me.mid
	midiconv.py -tv 4 0 0 -tv -1 1 0 $< $@
